### ISSUE TITLE
Unshallow flag breaks build on gitlab

### ISSUE THREAD

**Issue by Swahjak** [jderusse/docker-gitsplit#18]
`git fetch --prune --unshallow || true` will give the following (non blocking) error on gitlab ci: `fatal: --unshallow on a complete repository does not make sense`. The thing is; due to the error it seems to skip the entire fetch leaving you without any branches and causing errors when executing ```gitsplit --ref "$CI_COMMIT_REF_NAME"```

On a side note; thank you for putting this together. It saved me a lot of time not having to figure out all the specifics on maintaining a monorepo :+1:

**Comment by jderusse** [comment]
what's about using `git fetch --prune --unshallow || git fetch --prune`?

**Comment by Swahjak** [comment]
That does seem to do the trick :+1:
