### ISSUE TITLE
Open to release ?

### ISSUE THREAD

**Issue by nervo** [jderusse/docker-gitsplit#8]
As seen on https://github.com/jderusse/docker-gitsplit/commit/ad203a5b3995b724ebe5c70e3b5dd7d98a240a58#diff-3254677a7917c6c01f55212f86c57fbfR3 you have just introduced a version notion, do you plan to tag github releases ?
Connected to docker automated builds ?

**Comment by jderusse** [comment]
The env variable `SPLITSH_VERSION` refere to the splitsh bin, not this project.(see https://github.com/splitsh/lite/releases)

I don't plan to maintain/support several releases of docker-gitsplit. Docker hub his configured to automaticaly build a new `latest` image of the `master` branch.

**Comment by nervo** [comment]
Allright, thx for informations :)
